DEBUG
2022-11-09 17:54:04,992
Using proactor: IocpProactor
INFO
2022-11-09 17:54:10,881
 "c:\Users\alexa\Desktop\pro_110822\pro_110822\socketconnection.py"
(<class 'OSError'>, OSError(10049, 'The requested address is not valid in its context', None, 10049, None), <traceback object at 0x000001C151A7E840>)
Traceback (most recent call last):
  File "c:\Users\alexa\Desktop\pro_110822\pro_110822\socketconnection.py", line 66, in connect_to_server
    self.s.connect((serverIP, port))
OSError: [WinError 10049] The requested address is not valid in its context

serverIP: 192.168.0.255
port: 12345
INFO
2022-11-09 17:54:12,900
 "c:\Users\alexa\Desktop\pro_110822\pro_110822\socketconnection.py"
(<class 'ConnectionRefusedError'>, ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061, None), <traceback object at 0x000001C1517E0040>)
Traceback (most recent call last):
  File "c:\Users\alexa\Desktop\pro_110822\pro_110822\socketconnection.py", line 66, in connect_to_server
    self.s.connect((serverIP, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

serverIP: 192.168.0.1
port: 12345
INFO
2022-11-09 17:54:15,214
 "c:\Users\alexa\Desktop\pro_110822\pro_110822\socketconnection.py"
(<class 'ConnectionRefusedError'>, ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061, None), <traceback object at 0x000001C15258A140>)
Traceback (most recent call last):
  File "c:\Users\alexa\Desktop\pro_110822\pro_110822\socketconnection.py", line 66, in connect_to_server
    self.s.connect((serverIP, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

serverIP: 192.168.0.7
port: 12345
DEBUG
2022-11-09 17:54:20,177
Using proactor: IocpProactor
INFO
2022-11-09 17:54:25,893
 "c:\Users\alexa\Desktop\pro_110822\pro_110822\socketconnection.py"
(<class 'OSError'>, OSError(10049, 'The requested address is not valid in its context', None, 10049, None), <traceback object at 0x000001C1529E8300>)
Traceback (most recent call last):
  File "c:\Users\alexa\Desktop\pro_110822\pro_110822\socketconnection.py", line 66, in connect_to_server
    self.s.connect((serverIP, port))
OSError: [WinError 10049] The requested address is not valid in its context

serverIP: 192.168.0.255
port: 12345
INFO
2022-11-09 17:54:27,913
 "c:\Users\alexa\Desktop\pro_110822\pro_110822\socketconnection.py"
(<class 'ConnectionRefusedError'>, ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061, None), <traceback object at 0x000001C1529E9380>)
Traceback (most recent call last):
  File "c:\Users\alexa\Desktop\pro_110822\pro_110822\socketconnection.py", line 66, in connect_to_server
    self.s.connect((serverIP, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

serverIP: 192.168.0.1
port: 12345
